[package]
name = "catone"
version = "1.0.0"
edition = "2021"
description = "Simple file archiver, written in Rust"
license = "MIT"
authors = ["itsgerliz"]

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }

[profile.release-stripped]
inherits = "release"
strip = true